// ============================================================================
// API 路由 — Auth.js 處理器 / API Route — Auth.js Handler
// ============================================================================
// 處理所有 NextAuth.js 認證路由：
// Handles all NextAuth.js authentication routes:
//   /api/auth/signin
//   /api/auth/signout
//   /api/auth/session
//   /api/auth/callback/google
//
// 此檔案由 Next.js App Router 約定自動產生。
// This file is auto-generated by Next.js App Router convention.
// 請勿重新命名此檔案或移動到其他位置。
// Do NOT rename this file or move it to a different location.
// ============================================================================

import { GET, POST } from '@/lib/auth';

export { GET, POST };
